# Generated by Django 6.0 on 2025-12-22 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=15, verbose_name='CPF')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='investors', to=settings.AUTH_USER_MODEL, verbose_name='Investidores')),
            ],
        ),
    ]
