# Generated by Django 6.0 on 2025-12-22 16:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, help_text='Valor Inicial do investimento.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Valor Mínimo = R$ 0,01')], verbose_name='Valor')),
                ('was_withdrawn', models.BooleanField(default=False, help_text='Campo bool responsável pela a atividade do investimento.', verbose_name='Foi retirado')),
                ('withdrawn_created_at', models.DateTimeField(blank=True, help_text='Data em que a retirada do investimento foi registrada.', null=True, verbose_name='Data da retirada')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Data de criação do investimento (pode ser data passada).', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investors.investor', verbose_name='Investidor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
